let themes = [
	{
css: "https://bootswatch.com/5/cerulean/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/cerulean/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/cerulean/bootstrap.min.css",
description: "A calm blue sky",
name: "Cerulean",
preview: "https://bootswatch.com/cerulean/",
scss: "https://bootswatch.com/5/cerulean/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/cerulean/_variables.scss",
thumbnail: "https://bootswatch.com/cerulean/thumbnail.png",
},
{
css: "https://bootswatch.com/5/cosmo/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/cosmo/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/cosmo/bootstrap.min.css",
description: "An ode to Metro",
name: "Cosmo",
preview: "https://bootswatch.com/cosmo/",
scss: "https://bootswatch.com/5/cosmo/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/cosmo/_variables.scss",
thumbnail: "https://bootswatch.com/cosmo/thumbnail.png",
},
{
css: "https://bootswatch.com/5/cyborg/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/cyborg/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/cyborg/bootstrap.min.css",
description: "Jet black and electric blue",
name: "Cyborg",
preview: "https://bootswatch.com/cyborg/",
scss: "https://bootswatch.com/5/cyborg/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/cyborg/_variables.scss",
thumbnail: "https://bootswatch.com/cyborg/thumbnail.png",
},
{
css: "https://bootswatch.com/5/darkly/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/darkly/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/darkly/bootstrap.min.css",
description: "Flatly in night mode",
name: "Darkly",
preview: "https://bootswatch.com/darkly/",
scss: "https://bootswatch.com/5/darkly/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/darkly/_variables.scss",
thumbnail: "https://bootswatch.com/darkly/thumbnail.png",
},
{
css: "https://bootswatch.com/5/flatly/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/flatly/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/flatly/bootstrap.min.css",
description: "Flat and modern",
name: "Flatly",
preview: "https://bootswatch.com/flatly/",
scss: "https://bootswatch.com/5/flatly/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/flatly/_variables.scss",
thumbnail: "https://bootswatch.com/flatly/thumbnail.png",
},
{
css: "https://bootswatch.com/5/journal/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/journal/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/journal/bootstrap.min.css",
description: "Crisp like a new sheet of paper",
name: "Journal",
preview: "https://bootswatch.com/journal/",
scss: "https://bootswatch.com/5/journal/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/journal/_variables.scss",
thumbnail: "https://bootswatch.com/journal/thumbnail.png",
},
{
css: "https://bootswatch.com/5/litera/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/litera/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/litera/bootstrap.min.css",
description: "The medium is the message",
name: "Litera",
preview: "https://bootswatch.com/litera/",
scss: "https://bootswatch.com/5/litera/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/litera/_variables.scss",
thumbnail: "https://bootswatch.com/litera/thumbnail.png",
},
{
css: "https://bootswatch.com/5/lumen/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/lumen/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/lumen/bootstrap.min.css",
description: "Light and shadow",
name: "Lumen",
preview: "https://bootswatch.com/lumen/",
scss: "https://bootswatch.com/5/lumen/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/lumen/_variables.scss",
thumbnail: "https://bootswatch.com/lumen/thumbnail.png",
},
{
css: "https://bootswatch.com/5/lux/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/lux/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/lux/bootstrap.min.css",
description: "A touch of class",
name: "Lux",
preview: "https://bootswatch.com/lux/",
scss: "https://bootswatch.com/5/lux/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/lux/_variables.scss",
thumbnail: "https://bootswatch.com/lux/thumbnail.png",
},
{
css: "https://bootswatch.com/5/materia/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/materia/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/materia/bootstrap.min.css",
description: "Material is the metaphor",
name: "Materia",
preview: "https://bootswatch.com/materia/",
scss: "https://bootswatch.com/5/materia/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/materia/_variables.scss",
thumbnail: "https://bootswatch.com/materia/thumbnail.png",
},
{
css: "https://bootswatch.com/5/minty/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/minty/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/minty/bootstrap.min.css",
description: "A fresh feel",
name: "Minty",
preview: "https://bootswatch.com/minty/",
scss: "https://bootswatch.com/5/minty/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/minty/_variables.scss",
thumbnail: "https://bootswatch.com/minty/thumbnail.png",
},
{
css: "https://bootswatch.com/5/morph/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/morph/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/morph/bootstrap.min.css",
description: "A neumorphic layer",
name: "Morph",
preview: "https://bootswatch.com/morph/",
scss: "https://bootswatch.com/5/morph/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/morph/_variables.scss",
thumbnail: "https://bootswatch.com/morph/thumbnail.png",
},
{
css: "https://bootswatch.com/5/pulse/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/pulse/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/pulse/bootstrap.min.css",
description: "A trace of purple",
name: "Pulse",
preview: "https://bootswatch.com/pulse/",
scss: "https://bootswatch.com/5/pulse/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/pulse/_variables.scss",
thumbnail: "https://bootswatch.com/pulse/thumbnail.png",
},
{
css: "https://bootswatch.com/5/quartz/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/quartz/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/quartz/bootstrap.min.css",
description: "A glassmorphic layer",
name: "Quartz",
preview: "https://bootswatch.com/quartz/",
scss: "https://bootswatch.com/5/quartz/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/quartz/_variables.scss",
thumbnail: "https://bootswatch.com/quartz/thumbnail.png",
},
{
css: "https://bootswatch.com/5/sandstone/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/sandstone/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/sandstone/bootstrap.min.css",
description: "A touch of warmth",
name: "Sandstone",
preview: "https://bootswatch.com/sandstone/",
scss: "https://bootswatch.com/5/sandstone/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/sandstone/_variables.scss",
thumbnail: "https://bootswatch.com/sandstone/thumbnail.png",
},
{
css: "https://bootswatch.com/5/simplex/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/simplex/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/simplex/bootstrap.min.css",
description: "Mini and minimalist",
name: "Simplex",
preview: "https://bootswatch.com/simplex/",
scss: "https://bootswatch.com/5/simplex/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/simplex/_variables.scss",
thumbnail: "https://bootswatch.com/simplex/thumbnail.png",
},
{
css: "https://bootswatch.com/5/sketchy/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/sketchy/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/sketchy/bootstrap.min.css",
description: "A hand-drawn look for mockups and mirth",
name: "Sketchy",
preview: "https://bootswatch.com/sketchy/",
scss: "https://bootswatch.com/5/sketchy/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/sketchy/_variables.scss",
thumbnail: "https://bootswatch.com/sketchy/thumbnail.png",
},
{
css: "https://bootswatch.com/5/slate/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/slate/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/slate/bootstrap.min.css",
description: "Shades of gunmetal gray",
name: "Slate",
preview: "https://bootswatch.com/slate/",
scss: "https://bootswatch.com/5/slate/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/slate/_variables.scss",
thumbnail: "https://bootswatch.com/slate/thumbnail.png",
},
{
css: "https://bootswatch.com/5/solar/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/solar/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/solar/bootstrap.min.css",
description: "A spin on Solarized",
name: "Solar",
preview: "https://bootswatch.com/solar/",
scss: "https://bootswatch.com/5/solar/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/solar/_variables.scss",
thumbnail: "https://bootswatch.com/solar/thumbnail.png",
},
{
css: "https://bootswatch.com/5/spacelab/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/spacelab/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/spacelab/bootstrap.min.css",
description: "Silvery and sleek",
name: "Spacelab",
preview: "https://bootswatch.com/spacelab/",
scss: "https://bootswatch.com/5/spacelab/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/spacelab/_variables.scss",
thumbnail: "https://bootswatch.com/spacelab/thumbnail.png",
},
{
css: "https://bootswatch.com/5/superhero/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/superhero/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/superhero/bootstrap.min.css",
description: "The brave and the blue",
name: "Superhero",
preview: "https://bootswatch.com/superhero/",
scss: "https://bootswatch.com/5/superhero/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/superhero/_variables.scss",
thumbnail: "https://bootswatch.com/superhero/thumbnail.png",
},
{
css: "https://bootswatch.com/5/united/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/united/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/united/bootstrap.min.css",
description: "Ubuntu orange and unique font",
name: "United",
preview: "https://bootswatch.com/united/",
scss: "https://bootswatch.com/5/united/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/united/_variables.scss",
thumbnail: "https://bootswatch.com/united/thumbnail.png",
},
{
css: "https://bootswatch.com/5/vapor/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/vapor/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/vapor/bootstrap.min.css",
description: "A cyberpunk aesthetic",
name: "Vapor",
preview: "https://bootswatch.com/vapor/",
scss: "https://bootswatch.com/5/vapor/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/vapor/_variables.scss",
thumbnail: "https://bootswatch.com/vapor/thumbnail.png",
},
{
css: "https://bootswatch.com/5/yeti/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/yeti/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/yeti/bootstrap.min.css",
description: "A friendly foundation",
name: "Yeti",
preview: "https://bootswatch.com/yeti/",
scss: "https://bootswatch.com/5/yeti/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/yeti/_variables.scss",
thumbnail: "https://bootswatch.com/yeti/thumbnail.png",
},
{
css: "https://bootswatch.com/5/zephyr/bootstrap.css",
cssCdn: "https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/zephyr/bootstrap.min.css",
cssMin: "https://bootswatch.com/5/zephyr/bootstrap.min.css",
description: "Breezy and beautiful",
name: "Zephyr",
preview: "https://bootswatch.com/zephyr/",
scss: "https://bootswatch.com/5/zephyr/_bootswatch.scss",
scssVariables: "https://bootswatch.com/5/zephyr/_variables.scss",
thumbnail: "https://bootswatch.com/zephyr/thumbnail.png",
}
];

//25 in total 